### ISSUE TITLE
Issue importing from blocks.py

### ISSUE THREAD

**Issue by cweems** [mvantellingen/wagtail-factories#1] opened 2016-12-21 20:09 UTC
Thanks for your work on this! I'm not sure if this was my fault, but I'm having trouble importing anything from blocks.py. Everything in factories.py works.

I was really hoping to find out what was wrong, but I haven't debugged it yet. Your init looks fine. Here's an example of the ImportError:

<img width="877" alt="screen shot 2016-12-21 at 12 00 37 pm" src="https://cloud.githubusercontent.com/assets/1418949/21404438/110f77ce-c776-11e6-9fd8-e322604a8f8e.png">

**Comment by mvantellingen** [comment] 2016-12-21 20:45
I think the issue is that the pypi release doesn't have the block support yet. Can you give master a try?

**Comment by maersu** [comment] 2017-01-04 08:06
I can confirm the issue is solved with `master`

**Comment by mvantellingen** [comment] 2017-02-09 22:06
Should be fixed with the release of 0.2

**Closed by mvantellingen** 2017-02-09 22:06 UTC
